In [1]:
import numpy as np

In [7]:
import numpy as np

np.random.seed(42)

heart_rate = np.random.randint(55, 110, size=(60, 24)).astype(float)

# introduce missing values
heart_rate[2, 5] = np.nan
heart_rate[18, 12] = np.nan
heart_rate[40, 20] = np.nan


In [9]:
heart_rate

array([[ 93., 106.,  83., ...,  78.,  98.,  84.],
       [ 92.,  56.,  75., ..., 105.,  61.,  75.],
       [ 63.,  93.,  72., ...,  90., 104.,  94.],
       ...,
       [100.,  91.,  75., ..., 107.,  80.,  95.],
       [ 89., 106.,  79., ...,  60., 107.,  78.],
       [ 87., 103.,  83., ...,  61.,  55.,  86.]], shape=(60, 24))

In [10]:
hourly_avg_heart_rate = np.nanmean(heart_rate, axis=0)
hourly_avg_heart_rate

array([82.53333333, 81.53333333, 81.45      , 85.23333333, 78.26666667,
       84.33898305, 82.83333333, 78.01666667, 83.18333333, 82.3       ,
       78.93333333, 83.98333333, 81.42372881, 82.93333333, 84.55      ,
       82.63333333, 84.08333333, 81.08333333, 82.05      , 79.85      ,
       81.52542373, 84.48333333, 83.56666667, 86.25      ])

In [11]:
abnormal_mask = (heart_rate < 60) | (heart_rate > 100)
abnormal_mask


array([[False,  True, False, ..., False, False, False],
       [False,  True, False, ...,  True, False, False],
       [False, False, False, ..., False,  True, False],
       ...,
       [False, False, False, ...,  True, False, False],
       [False,  True, False, ..., False,  True, False],
       [False,  True, False, ..., False,  True, False]], shape=(60, 24))

In [12]:
filled_heart_rate = heart_rate.copy()

for patient in range(filled_heart_rate.shape[0]):
    for hour in range(1, filled_heart_rate.shape[1]):
        if np.isnan(filled_heart_rate[patient, hour]):
            filled_heart_rate[patient, hour] = filled_heart_rate[patient, hour - 1]


In [13]:
filled_heart_rate

array([[ 93., 106.,  83., ...,  78.,  98.,  84.],
       [ 92.,  56.,  75., ..., 105.,  61.,  75.],
       [ 63.,  93.,  72., ...,  90., 104.,  94.],
       ...,
       [100.,  91.,  75., ..., 107.,  80.,  95.],
       [ 89., 106.,  79., ...,  60., 107.,  78.],
       [ 87., 103.,  83., ...,  61.,  55.,  86.]], shape=(60, 24))