In [1]:
import numpy as np

In [10]:
np.random.seed(1)
s=np.random.randint(1,30,size=(14,6))

In [11]:
s

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14, 29,  7, 26, 19],
       [21,  6, 19, 21, 12, 29],
       [11, 29, 15, 19,  5, 24],
       [24, 10, 18, 24,  1, 23],
       [14, 10, 10,  8, 23, 26],
       [ 2,  1, 29, 18,  9, 25],
       [14, 20, 16, 11, 26,  9],
       [ 8,  4,  7, 22, 18, 26],
       [ 4,  5, 25, 18, 12, 13],
       [27, 21, 17, 14, 20, 10],
       [19, 16,  1,  5, 26, 16],
       [ 3, 24,  8, 27, 26,  9]], dtype=int32)

In [13]:
time = np.sum(s,axis=0)
time

array([167, 188, 208, 220, 216, 254])

In [14]:
avg = np.mean(s, axis=0)
avg

array([11.92857143, 13.42857143, 14.85714286, 15.71428571, 15.42857143,
       18.14285714])

In [15]:
threshold = 70
high_course = avg>threshold

In [16]:
avg
high_course

array([False, False, False, False, False, False])

In [17]:
ranking = np.argsort(avg)[::-1]
ranking

array([5, 3, 4, 2, 1, 0])