In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [3]:
data = np.random.randint(-25,100,size=(30,5))

In [4]:
data

array([[ 12,  82, -13,  47, -16],
       [ 50, -20,  54,  39,  -9],
       [-24,  51,  46,  84,  99],
       [-19,   0,  25,  -5,  76],
       [ -7,  59, -14,  99,  81],
       [  3,   4, -11,  25,  43],
       [ 62,  62,  80,  88,  94],
       [ 69,  71,  61, -12,  80],
       [-16, -18,  38,  36,  -3],
       [ 32, -24, -25,  35,  56],
       [-17,  63, -12,  90,  22],
       [ 81,  96,  47,   5,  46],
       [-22,  45,  -4,  24,  32],
       [-22,  43,  -1,  88,  18],
       [ 51,   1,  27,  55,  84],
       [ 90,  16,  57, -10,  39],
       [ 43,   0,  86,  73,  62],
       [-18,   1,   0,  79,  -3],
       [-16,  42,  78,  -2,  75],
       [  2,  12,  32,  58,  13],
       [-17,   7,   9, -15,  -2],
       [-10,  86,  62,   0,  46],
       [ 90,  67,  49,  37,  21],
       [  7,  63,  -2,  30,  40],
       [ 88,  52, -22, -25,  95],
       [ 52, -19,  27,  60,  45],
       [-23,  51,  66,  -4,  50],
       [-18,  52,  47,  50,  51],
       [ 18,  -5,   5,  11,  78],
       [-18,  

In [ ]:
# Im replacing here negative values
data[data<0] = 0

In [6]:
data

array([[12, 82,  0, 47,  0],
       [50,  0, 54, 39,  0],
       [ 0, 51, 46, 84, 99],
       [ 0,  0, 25,  0, 76],
       [ 0, 59,  0, 99, 81],
       [ 3,  4,  0, 25, 43],
       [62, 62, 80, 88, 94],
       [69, 71, 61,  0, 80],
       [ 0,  0, 38, 36,  0],
       [32,  0,  0, 35, 56],
       [ 0, 63,  0, 90, 22],
       [81, 96, 47,  5, 46],
       [ 0, 45,  0, 24, 32],
       [ 0, 43,  0, 88, 18],
       [51,  1, 27, 55, 84],
       [90, 16, 57,  0, 39],
       [43,  0, 86, 73, 62],
       [ 0,  1,  0, 79,  0],
       [ 0, 42, 78,  0, 75],
       [ 2, 12, 32, 58, 13],
       [ 0,  7,  9,  0,  0],
       [ 0, 86, 62,  0, 46],
       [90, 67, 49, 37, 21],
       [ 7, 63,  0, 30, 40],
       [88, 52,  0,  0, 95],
       [52,  0, 27, 60, 45],
       [ 0, 51, 66,  0, 50],
       [ 0, 52, 47, 50, 51],
       [18,  0,  5, 11, 78],
       [ 0, 20, 43, 32, 87]], dtype=int32)

In [ ]:
# here im calculating for only 28 days
weeks = 4
days = 7
sales = data[:weeks*days]

In [10]:
sales

array([[12, 82,  0, 47,  0],
       [50,  0, 54, 39,  0],
       [ 0, 51, 46, 84, 99],
       [ 0,  0, 25,  0, 76],
       [ 0, 59,  0, 99, 81],
       [ 3,  4,  0, 25, 43],
       [62, 62, 80, 88, 94],
       [69, 71, 61,  0, 80],
       [ 0,  0, 38, 36,  0],
       [32,  0,  0, 35, 56],
       [ 0, 63,  0, 90, 22],
       [81, 96, 47,  5, 46],
       [ 0, 45,  0, 24, 32],
       [ 0, 43,  0, 88, 18],
       [51,  1, 27, 55, 84],
       [90, 16, 57,  0, 39],
       [43,  0, 86, 73, 62],
       [ 0,  1,  0, 79,  0],
       [ 0, 42, 78,  0, 75],
       [ 2, 12, 32, 58, 13],
       [ 0,  7,  9,  0,  0],
       [ 0, 86, 62,  0, 46],
       [90, 67, 49, 37, 21],
       [ 7, 63,  0, 30, 40],
       [88, 52,  0,  0, 95],
       [52,  0, 27, 60, 45],
       [ 0, 51, 66,  0, 50],
       [ 0, 52, 47, 50, 51]], dtype=int32)

In [ ]:
# here im reshaping based on week , days, products
products = 5
weekly_sales = sales.reshape(weeks,days,products)

In [13]:
weekly_sales

array([[[12, 82,  0, 47,  0],
        [50,  0, 54, 39,  0],
        [ 0, 51, 46, 84, 99],
        [ 0,  0, 25,  0, 76],
        [ 0, 59,  0, 99, 81],
        [ 3,  4,  0, 25, 43],
        [62, 62, 80, 88, 94]],

       [[69, 71, 61,  0, 80],
        [ 0,  0, 38, 36,  0],
        [32,  0,  0, 35, 56],
        [ 0, 63,  0, 90, 22],
        [81, 96, 47,  5, 46],
        [ 0, 45,  0, 24, 32],
        [ 0, 43,  0, 88, 18]],

       [[51,  1, 27, 55, 84],
        [90, 16, 57,  0, 39],
        [43,  0, 86, 73, 62],
        [ 0,  1,  0, 79,  0],
        [ 0, 42, 78,  0, 75],
        [ 2, 12, 32, 58, 13],
        [ 0,  7,  9,  0,  0]],

       [[ 0, 86, 62,  0, 46],
        [90, 67, 49, 37, 21],
        [ 7, 63,  0, 30, 40],
        [88, 52,  0,  0, 95],
        [52,  0, 27, 60, 45],
        [ 0, 51, 66,  0, 50],
        [ 0, 52, 47, 50, 51]]], dtype=int32)

In [15]:
week_total = weekly_sales.sum(axis=1)

In [16]:
week_total

array([[127, 258, 205, 382, 393],
       [182, 318, 146, 278, 254],
       [186,  79, 289, 265, 273],
       [237, 371, 251, 177, 348]])

In [19]:
avg = week_total.mean(axis=0)

In [ ]:
# average weekly sales
avg

array([183.  , 256.5 , 222.75, 275.5 , 317.  ])

In [ ]:
# highest average weekly sales index
highestavg = np.argmax(avg)

np.int64(4)

In [30]:
print(highestavg + 1)

5


In [29]:
print(avg)

[183.   256.5  222.75 275.5  317.  ]
