In [2]:
import numpy as np

In [3]:
s = np.random.randint(15,40, size=(7,24))

In [4]:
s

array([[31, 32, 26, 20, 39, 29, 18, 30, 20, 28, 20, 34, 15, 34, 24, 32,
        26, 15, 29, 29, 19, 39, 23, 17],
       [19, 37, 34, 24, 37, 37, 32, 27, 16, 18, 17, 28, 31, 22, 39, 38,
        28, 24, 37, 20, 16, 27, 16, 20],
       [22, 35, 28, 27, 35, 21, 25, 22, 28, 23, 27, 15, 31, 38, 29, 26,
        30, 27, 38, 30, 30, 33, 34, 35],
       [33, 27, 19, 31, 36, 17, 28, 26, 19, 22, 32, 15, 21, 27, 39, 23,
        33, 29, 24, 24, 25, 23, 19, 31],
       [39, 25, 22, 17, 31, 35, 38, 35, 29, 39, 32, 33, 39, 26, 24, 28,
        15, 39, 29, 26, 20, 39, 38, 34],
       [30, 35, 38, 28, 33, 18, 27, 28, 21, 21, 16, 35, 17, 38, 29, 21,
        20, 26, 24, 18, 23, 23, 18, 38],
       [15, 30, 17, 22, 19, 32, 29, 34, 30, 21, 27, 33, 18, 38, 35, 23,
        25, 32, 26, 22, 22, 18, 25, 24]], dtype=int32)

In [5]:
max_temp = np.max(s, axis=1)

In [6]:
min_temp = np.min(s,axis=1)

In [7]:
max_temp

array([39, 39, 38, 39, 39, 38, 38], dtype=int32)

In [14]:
day_variation = max_temp-min_temp

In [11]:
day_variation

array([24, 23, 23, 24, 24, 22, 23], dtype=int32)

In [15]:
print(day_variation)

[24 23 23 24 24 22 23]


In [16]:
mean_temp = np.mean(s)
std_temp = np.std(s)

In [17]:
lower_bound = mean_temp - 2 * std_temp
upper_bound = mean_temp + 2 * std_temp

In [19]:
temps_cleaned = s.copy()
temps_cleaned[(s < lower_bound) | (s > upper_bound)] = mean_temp

In [23]:
temps_cleaned

array([[31, 32, 26, 20, 39, 29, 18, 30, 20, 28, 20, 34, 15, 34, 24, 32,
        26, 15, 29, 29, 19, 39, 23, 17],
       [19, 37, 34, 24, 37, 37, 32, 27, 16, 18, 17, 28, 31, 22, 39, 38,
        28, 24, 37, 20, 16, 27, 16, 20],
       [22, 35, 28, 27, 35, 21, 25, 22, 28, 23, 27, 15, 31, 38, 29, 26,
        30, 27, 38, 30, 30, 33, 34, 35],
       [33, 27, 19, 31, 36, 17, 28, 26, 19, 22, 32, 15, 21, 27, 39, 23,
        33, 29, 24, 24, 25, 23, 19, 31],
       [39, 25, 22, 17, 31, 35, 38, 35, 29, 39, 32, 33, 39, 26, 24, 28,
        15, 39, 29, 26, 20, 39, 38, 34],
       [30, 35, 38, 28, 33, 18, 27, 28, 21, 21, 16, 35, 17, 38, 29, 21,
        20, 26, 24, 18, 23, 23, 18, 38],
       [15, 30, 17, 22, 19, 32, 29, 34, 30, 21, 27, 33, 18, 38, 35, 23,
        25, 32, 26, 22, 22, 18, 25, 24]], dtype=int32)